//
//  Bundle+Resources.swift
//  KeyboardKit
//
//  Created by Antoine Baché on 2021-01-23.
//  Copyright © 2017 Daniel Saidi. All rights reserved.
//

import Foundation

/**
 This file is ignored when using SPM directly. It is however
 kept when using CocoaPods, where the autogenerated `module`
 bundle is not present.
 */
extension Bundle {
    
    /**
     This is the bundle of the KeyboardKit library.
     */
    static var module: Bundle = {
        Bundle(for: Token.self)
    }()
}

private final class Token {}
